### model
model_name_or_path: /data/koushurui/Code/LLMS/Qwen/Qwen2.5-Coder-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: dail_bird_origin
template: qwen
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 0
flash_attn: fa2

### output
output_dir: /data/koushurui/Code/LLMS/Qwen/Qwen2.5-Coder-7B-Instruct-BIRD-SFT
logging_steps: 10

save_steps: 2000
plot_loss: true
save_strategy: steps
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
weight_decay: 0.01
max_grad_norm: 0.3
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
optim: adamw_torch_fused
gradient_checkpointing: true

### eval
eval_dataset: dail_bird_eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500